#!/usr/bin/env bash
#PANDOC_IMAGE='ghcr.io/hg-jt/pandoc-texlive:latest'
PANDOC_IMAGE='ghcr.io/hg-jt/pandoc-texlive:main'
PANDOC_TEX_TEMPLATE='notes'
PDF_ENGINE='xelatex'
PDF_ENGINE_OPT=-shell-escape  #  -output-driver="xdvipdfmx -z 0"
OUTPUT_DOCX='false'
OUTPUT_HTML='false'
OUTPUT_PDF='false'
OUTPUT_TEX='false'
OUTPUT_TEXTILE='false'
MARKDOWN_FEATURES='markdown+pipe_tables+table_captions+raw_tex+strikeout+task_lists'


function log() {
  >&2 echo $@;
}

function usage() {
  >&2 cat <<EOF
NAME
    $(basename $0) - pandoc wrapper

SYNOPSIS
    $(basename $0) [-h] [-H] [-p] [-t] [-w]  SOURCE_FILE [ADDITIONAL_PANDOC_ARGS]

DESCRIPTION
    pd is a convienence script for calling Pandoc inside a docker
    container. The default configuration assumes Markdown input
    and PDF output, however the input can by any format supported
    by pandoc.

    When options are provided, they will trigger the genration of
    additional output formats (i.e. the PDF will still be generated).

OPTIONS
     -h   Print usage message.

     -H   Generate HTML output.

     -p   Generate PDF output.

     -t   Generate tex output.

     -T   Generate textile output.

     -w   Generate docx output.
EOF
}

# ensure $name is unset to detect no args
test -z "$name" && unset name

# parse command line args
while getopts ':hHptTw' opt; do
  case "$opt" in
    h)
      usage
      exit 0
      ;;
    H)
      OUTPUT_HTML='true'
      ;;
    p)
      OUTPUT_PDF='true'
      ;;
    t)
      OUTPUT_TEX='true'
      ;;
    T)
      OUTPUT_TEXTILE='true'
      ;;
    w)
      OUTPUT_DOCX='true'
      ;;
    ?)
      log "Invalid command line option: ${OPTARG}.\n\n"
      usage
      exit 1
      ;;
  esac
done

# set default options if none provided
if [ -z "$name" ]; then
  OUTPUT_PDF='true'
fi

# get filename as positional arg
srcfile=${@:$OPTIND:1}

if [ -z "$srcfile" ]; then
  log "ERROR: a source file is required."
  exit 1
fi

#if [ ! -f "$srcfile" ]; then
#  log "$srcfile does not exist!"
#  exit 1
#fi

if [ "$srcfile" = "-" ]; then
  extension="md"
  filename=${@:$OPTIND+1:1}
else
  extension="${srcfile##*.}"
  filename="${srcfile%.*}"
fi

if $OUTPUT_DOCX; then
  docker run \
    --rm \
    -i \
    -v "$(pwd)":/docs \
    $PANDOC_IMAGE \
    -s \
    --syntax-highlighting=none \
    -o ${filename}.docx \
    ${srcfile}
fi

if $OUTPUT_HTML; then
  docker run \
    --rm \
    -i \
    -v "$(pwd)":/docs \
    $PANDOC_IMAGE \
    -s \
    --syntax-highlighting=none  \
    -V mainfont="Helvetica, sans-serif" \
    -o ${filename}.html \
    ${srcfile}
fi

if $OUTPUT_TEX; then
  docker run \
    --rm \
    -i \
    -v "$(pwd)":/docs \
    $PANDOC_IMAGE \
    --template=${PANDOC_TEX_TEMPLATE} \
    -s \
    --pdf-engine=${PDF_ENGINE} \
    --pdf-engine-opt=${PDF_ENGINE_OPT} \
    --syntax-highlighting=idiomatic \
    --from $MARKDOWN_FEATURES \
    --lua-filter=diagram-generator.lua \
    -V colorlinks=true \
    -o ${filename}.tex \
    ${srcfile}
fi

if $OUTPUT_PDF; then
  docker run \
    --rm \
    -i \
    -v "$(pwd)":/docs \
    $PANDOC_IMAGE \
    --template=${PANDOC_TEX_TEMPLATE} \
    -s \
    --pdf-engine=${PDF_ENGINE} \
    --pdf-engine-opt=${PDF_ENGINE_OPT} -output-driver="xdvipdfmx -z 0" \
    --syntax-highlighting=idiomatic \
    --from $MARKDOWN_FEATURES \
    --lua-filter=diagram-generator.lua \
    -V colorlinks=true \
    -V author=true \
    -o ${filename}.pdf \
    ${srcfile}
fi

if $OUTPUT_TEXTILE; then
  docker run \
    --rm \
    -i \
    -v "$(pwd)":/docs \
    $PANDOC_IMAGE \
    -s \
    --from $MARKDOWN_FEATURES \
    -o ${filename}.textile \
    ${srcfile}
fi
